import "../../styles/global.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import NavigationBar from "./ui/Navbar";
import SideBar from "./ui/Sidebar";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, // 페이지 또는 nested layout
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <AntdRegistry>
            <NavigationBar />
            <SideBar />
            {children}
          </AntdRegistry>
        </Providers>
      </body>
    </html>
  );
}
